### ISSUE TITLE
normalisation and discretisation

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR-GATE-Connection#57]
- The phantom used for the normalisation uses 1 sample per voxel, leading to a jaged boundary. Things will work better when using more samples here https://github.com/UCL/STIR-GATE-Connection/blob/dc58ecadbcf20706ebea94846faf77eef7d5a383/ExamplePhantoms/STIRparFiles/D690FOVCylinder.par#L20-L22
- Normalisation factors depend on the projector. We currently use the default projector, which is the ray-tracing matrix with a single LOR. This has its own discretisation errors, which don't really match what GATE does. The estimated efficiencies therefore try to compensate for this, but this means they are not very good for smaller phantoms. Recommended therefore to use [a par file](https://github.com/UCL/STIR/blob/master/examples/samples/forward_projector_proj_matrix_ray_tracing.par) saying `number of rays in tangential direction to trace for each bin:= 5` or similar here https://github.com/UCL/STIR-GATE-Connection/blob/dc58ecadbcf20706ebea94846faf77eef7d5a383/VoxelisedSimulation/SubScripts/EstimateGATESTIRNorm.sh#L54

Note that the doc should make it clear that the norm factors are for the given projector.

**Comment by robbietuk** [comment]
Im curious as to how this impact the normalisation sinogram? For this phantom, the edge of the cylinders **_should_** actually be just outside of the FOV, **_should_** being the key word.

**Comment by robbietuk** [comment]
After a small investigation, the impact of the discretisation of the generated `D690FOVCylinder.par` phantom, there are indeed edge artefacts.

The difference between phatoms generated with 1 and 3 samples to take per voxel
![image](https://user-images.githubusercontent.com/13292409/106132351-bfa34a80-615b-11eb-99df-45c3142756f1.png)

The difference between phatoms generated  with 3 and 5 samples to take per voxel
![image](https://user-images.githubusercontent.com/13292409/106132466-e2cdfa00-615b-11eb-9307-796384c9c849.png)

The cylinder has intensity 10.

**Comment by KrisThielemans** [comment]
yes, all differences are at the edges, as with 1 sample, it takes a 0/1 approach, while with 27 samples it allows graduations  with increment 1/27

Arguably the more interesting one is the projector. At some point, @francescaleek can show efficiency factors estimated with the "1 LOR" and "multiple LOR" projectors. You'll see the difference.

**Comment by robbietuk** [comment]
Time for a Data Dump. I think this is the best platform for this.

> **Discretisation results** 

Minor change in the normalisation sinogram (SSRB'ed difference). This did not involve the rerunning of GATE similations on the new discretised D690FOVCylidner. It would be interesting to see the impact, but I imagine it to be small. 

![image](https://user-images.githubusercontent.com/13292409/106445960-96dec600-6477-11eb-935f-37d2830e3ddc.png)
Currently used:
![image](https://user-images.githubusercontent.com/13292409/106445984-9e05d400-6477-11eb-9d74-f43cc9b29891.png)
The difference is 0.3% at max. Obviously annoying but little evidence that rerunning GATE simulations will result in dramatically different results. 

 

> **Projector:**

The impact due to a different projector is even more surprising with very little difference in normalisation sinograms. This uses the code in the PR. The difference image compares the impact of projector with `number of rays in tangential direction to trace for each bin:= 1` and `number of rays in tangential direction to trace for each bin:= 10` in the forward projection. 

Images have been SSRB'ed (differences should primarily be transaxial?)
![image](https://user-images.githubusercontent.com/13292409/106449291-ba0b7480-647b-11eb-8f13-337b7fa7214c.png)

![image](https://user-images.githubusercontent.com/13292409/106449267-b4159380-647b-11eb-958e-4a9f7d61c5b3.png)

This makes me think that something else is wrong as the errors are at max 0.06%.

@francescaleek is this something you see?


> **Difference between forward projections**

I have also checked to see the difference between the different STIR forward projectors for the D690FOVCylinder phantom. The difference here is small and I do not see vertical lines, at least not in these SSRB images.
![image](https://user-images.githubusercontent.com/13292409/106452732-30aa7100-6480-11eb-972f-c4dc19ecd0e3.png)
![image](https://user-images.githubusercontent.com/13292409/106452787-43bd4100-6480-11eb-9ccc-277a60ea541d.png)

Without SSRB, the slice by slice comparisons show very similar results with very small max change.
